### PR TITLE
Add aggregation types

### PR DESCRIPTION
**Pull request by turnerniles**
Adds aggregation types average, min and max.

### CODE REVIEW

**Comment by turnerniles** [comment]
Ok I see I have to write tests to test the accumulators for the quick-pivot.js build file.

**Comment by turnerniles** [comment]
Should we create an expected results file to store the expectedData? logic.spec.js is getting long and has these massive expectedData variables.

**Comment by pat310** [comment]
@turnerniles Yup, good idea

**Comment by pat310** [comment]
@turnerniles Pull and merge master

**Comment by pat310** [comment]
@turnerniles nm, I got it

**Pull request merged**
